const Database = require('better-sqlite3')
const db = new Database("db.txt")

module.exports = async (client, message, args, Discord, mongoose, Schemas) => {
  var companys = mongoose.model("companie", Schemas.companies)
  var company = (await companys.find()).find(company => company.users.includes(message.author.id))
  var requests = mongoose.model("crequest", Schemas.crequests)
  if (!company) return message.reply("You aren't in a company!")
  if (company.owner !== message.author.id) return message.reply("You can't invite this person since you don't own this company.")
  var user = message.mentions.users.first() || client.users.cache.get(args[2])
  if (!user) return message.reply("Please provide a user to invite.")
  var usercompany = (await companys.find()).find(company => company.users.includes(user.id))
  var userrequests = await requests.findById(user.id)
  if (usercompany) return message.reply(`${user.tag} is already in a company.`)
  if (!userrequests) userrequests = await new requests({ _id: user.id, requests: [] }).save()
  if (userrequests.requests.includes(company.name)) return message.reply("This user has already been invited to " + company.name + ".")
  message.reply(`Invited ${user.tag} to ${company.name}!`)
  userrequests.requests.push(company.name)
  userrequests.save()
}